Repository DeveloperAcademy-POSTECH/2025-C4-M10-ProudlyOffbeat, pull requests merged in 2025-07, with the labels that each got.

#25 feat/#15/HomeLibraryView UI 구현
  LivingStory-iOS/LivingStory-iOS.xcodeproj/project.pbxproj
  LivingStory-iOS/LivingStory-iOS/App/Coordinator/AppRoute.swift
  LivingStory-iOS/LivingStory-iOS/App/Factory/ModuleFactory.swift
  LivingStory-iOS/LivingStory-iOS/App/RootNavigationView.swift
  LivingStory-iOS/LivingStory-iOS/Assets.xcassets/Frame.imageset/Contents.json
  LivingStory-iOS/LivingStory-iOS/Assets.xcassets/Frame.imageset/Frame.png
  LivingStory-iOS/LivingStory-iOS/Assets.xcassets/HomeBackground.imageset/HomeBackground.jpg
  LivingStory-iOS/LivingStory-iOS/iPad/Library/HomeLibraryView.swift
  LivingStory-iOS/LivingStory-iOS/iPad/Library/Model/BookModel.swift
  LivingStory-iOS/LivingStory-iOS/iPad/Library/View/FrameView.swift
  LivingStory-iOS/LivingStory-iOS/iPad/Library/View/HomeDoorView.swift
  LivingStory-iOS/LivingStory-iOS/iPad/Library/ViewModel/HomeLibraryViewModel.swift
  LivingStory-iOS/LivingStory-iOS/iPad/iPhonePairing/iPhonePairingView.swift
  LivingStory-iOS/LivingStory-iOS/iPad/iPhonePairing/iPhonePairingViewModel.swift
Labels: 🔥Feature, 💪Ito

#28 feat/#16/iPhonePairingView
  LivingStory-iOS/LivingStory-iOS.xcodeproj/project.pbxproj
  LivingStory-iOS/LivingStory-iOS/Assets.xcassets/ConnectListBackground.imageset/ConnectListRectangle.png
  LivingStory-iOS/LivingStory-iOS/Assets.xcassets/ConnectListBackground.imageset/Contents.json
  LivingStory-iOS/LivingStory-iOS/Assets.xcassets/iPhoneNotice.imageset/Contents.json
  LivingStory-iOS/LivingStory-iOS/Assets.xcassets/iPhoneNotice.imageset/iPhoneNotice.png
  LivingStory-iOS/LivingStory-iOS/iPad/iPhonePairing/Model/PeerModel.swift
  LivingStory-iOS/LivingStory-iOS/iPad/iPhonePairing/View/ConnectCellView.swift
  LivingStory-iOS/LivingStory-iOS/iPad/iPhonePairing/View/ConnectListView.swift
  LivingStory-iOS/LivingStory-iOS/iPad/iPhonePairing/View/PairingBookView.swift
  LivingStory-iOS/LivingStory-iOS/iPad/iPhonePairing/View/iPhoneNoticeView.swift
  LivingStory-iOS/LivingStory-iOS/iPad/iPhonePairing/View/iPhonePairingBackgroundView.swift
  LivingStory-iOS/LivingStory-iOS/iPad/iPhonePairing/ViewModel/iPhonePairingViewModel.swift
  LivingStory-iOS/LivingStory-iOS/iPad/iPhonePairing/iPhonePairingView.swift
Labels: 🔥Feature, 💪Ito

#40 Feat/#38/home library view logic
  LivingStory-iOS/LivingStory-iOS.xcodeproj/project.pbxproj
  LivingStory-iOS/LivingStory-iOS/Assets.xcassets/HeungDoor.imageset/HeuongDoor.png
  LivingStory-iOS/LivingStory-iOS/Assets.xcassets/HomeLibraryView/Contents.json
  LivingStory-iOS/LivingStory-iOS/Assets.xcassets/HomeLibraryView/Frame.imageset/Contents.json
  LivingStory-iOS/LivingStory-iOS/Assets.xcassets/HomeLibraryView/Frame.imageset/Frame.png
  LivingStory-iOS/LivingStory-iOS/Assets.xcassets/HomeLibraryView/HeungDoor.imageset/Contents.json
  LivingStory-iOS/LivingStory-iOS/Assets.xcassets/HomeLibraryView/HeungDoor.imageset/HeungDoor.png
  LivingStory-iOS/LivingStory-iOS/Assets.xcassets/HomeLibraryView/HomeBackground.imageset/Contents.json
  LivingStory-iOS/LivingStory-iOS/Assets.xcassets/HomeLibraryView/HomeBackground.imageset/HomeBackground.jpg
  LivingStory-iOS/LivingStory-iOS/Assets.xcassets/HomeLibraryView/OzDoor.imageset/Contents.json
  LivingStory-iOS/LivingStory-iOS/Assets.xcassets/HomeLibraryView/OzDoor.imageset/OzDoor.png
  LivingStory-iOS/LivingStory-iOS/Assets.xcassets/HomeLibraryView/PigDoor.imageset/Contents.json
  LivingStory-iOS/LivingStory-iOS/Assets.xcassets/HomeLibraryView/PigDoor.imageset/PigDoor.png
  LivingStory-iOS/LivingStory-iOS/Assets.xcassets/OzDoor.imageset/OzDoor.png
  LivingStory-iOS/LivingStory-iOS/Assets.xcassets/PigDoor.imageset/PigDoor.png
  LivingStory-iOS/LivingStory-iOS/iPad/Library/HomeLibraryView.swift
  LivingStory-iOS/LivingStory-iOS/iPad/Library/View/HomeDoorView.swift
  LivingStory-iOS/LivingStory-iOS/iPad/Library/View/HomeInfoFrameView.swift
  LivingStory-iOS/LivingStory-iOS/iPad/Library/ViewModel/HomeLibraryViewModel.swift
Labels: 🔥Feature, 💪Ito

#45 feat/#41/iPhoneFairyTaleView
  LivingStory-iOS/LivingStory-iOS.xcodeproj/project.pbxproj
  LivingStory-iOS/LivingStory-iOS/Core/Resources/Assets.xcassets/PigCover.imageset/Contents.json
  LivingStory-iOS/LivingStory-iOS/Core/Resources/Assets.xcassets/PigCover.imageset/PigCover3.png
  LivingStory-iOS/LivingStory-iOS/iPhone/iPadPairing/SubView/ConnectButtonView.swift
  LivingStory-iOS/LivingStory-iOS/iPhone/iPhoneFairyTale/FairyTaleStatusView.swift
  LivingStory-iOS/LivingStory-iOS/iPhone/iPhoneFairyTale/iPhoneFairyTaleView.swift
Labels: 🔥Feature, 👹Martin

#54 feat/#46/iPadPairingView UI 수정
  LivingStory-iOS/LivingStory-iOS/Core/Resources/Assets.xcassets/Room(cut).imageset/Contents.json
  LivingStory-iOS/LivingStory-iOS/Core/Resources/Assets.xcassets/Room(cut).imageset/Room(cut).jpg
  LivingStory-iOS/LivingStory-iOS/iPhone/iPadPairing/SubView/ConnectButtonView.swift
  LivingStory-iOS/LivingStory-iOS/iPhone/iPadPairing/SubView/WifiConnectView.swift
  LivingStory-iOS/LivingStory-iOS/iPhone/iPadPairing/iPadPairingView.swift
Labels: 🔥Feature, 👹Martin

#58 Feat/#50/factory di working 및 MCP 모든 예외 처리 완료
  LivingStory-iOS/LivingStory-iOS.xcodeproj/project.pbxproj
  LivingStory-iOS/LivingStory-iOS/.cursor/rules/swift-ui-rule.mdc
  LivingStory-iOS/LivingStory-iOS/.cursor/rules/todolist.mdc
  LivingStory-iOS/LivingStory-iOS/App/Coordinator/AppCoordinator.swift
  LivingStory-iOS/LivingStory-iOS/App/Coordinator/AppRoute.swift
  LivingStory-iOS/LivingStory-iOS/App/Factory/ModuleFactory.swift
  LivingStory-iOS/LivingStory-iOS/App/RootNavigationView.swift
  LivingStory-iOS/LivingStory-iOS/Core/Components/Alerts/ConnectedAlert.swift
  LivingStory-iOS/LivingStory-iOS/Core/Components/Alerts/DisconnectedAlert.swift
  LivingStory-iOS/LivingStory-iOS/Core/Components/Alerts/FromiPadConnectedAlert.swift
  LivingStory-iOS/LivingStory-iOS/Core/Components/Alerts/NonconnectionAlert.swift
  LivingStory-iOS/LivingStory-iOS/Core/Modules/MultipeerModule/MultipeerManager+Extension.swift
  LivingStory-iOS/LivingStory-iOS/Core/Modules/MultipeerModule/MultipeerManager.swift
  LivingStory-iOS/LivingStory-iOS/Core/Modules/MultipeerModule/MultipeerModels.swift
  LivingStory-iOS/LivingStory-iOS/Core/Resources/Assets.xcassets/iPadFairyTaleView/Light.imageset/Contents.json
  LivingStory-iOS/LivingStory-iOS/Core/Resources/Assets.xcassets/iPadFairyTaleView/Light.imageset/등불 1.png
  LivingStory-iOS/LivingStory-iOS/iPad/Library/HomeLibraryView.swift
  LivingStory-iOS/LivingStory-iOS/iPad/Library/Model/BookType+Extension.swift
  LivingStory-iOS/LivingStory-iOS/iPad/Library/ViewModel/HomeLibraryViewModel.swift
  LivingStory-iOS/LivingStory-iOS/iPad/iPadFairyTale/ViewModel/iPadFairyTaleViewModel.swift
  LivingStory-iOS/LivingStory-iOS/iPad/iPadFairyTale/iPadFairyTaleView.swift
  LivingStory-iOS/LivingStory-iOS/iPad/iPhonePairing/ConnectListView.swift
  LivingStory-iOS/LivingStory-iOS/iPad/iPhonePairing/PairingBookView.swift
  LivingStory-iOS/LivingStory-iOS/iPad/iPhonePairing/View/PairingBookView.swift
  LivingStory-iOS/LivingStory-iOS/iPad/iPhonePairing/View/SubView/ConnectCellView.swift
  LivingStory-iOS/LivingStory-iOS/iPad/iPhonePairing/View/SubView/ConnectListScrollView.swift
  LivingStory-iOS/LivingStory-iOS/iPad/iPhonePairing/View/SubView/ConnectListView.swift
  LivingStory-iOS/LivingStory-iOS/iPad/iPhonePairing/View/SubView/ConnectRightPageView.swift
  LivingStory-iOS/LivingStory-iOS/iPad/iPhonePairing/View/SubView/PeerConnectButtonView.swift
  LivingStory-iOS/LivingStory-iOS/iPad/iPhonePairing/ViewModel/iPhonePairingViewModel.swift
  LivingStory-iOS/LivingStory-iOS/iPad/iPhonePairing/iPhonePairingBackgroundView.swift
  LivingStory-iOS/LivingStory-iOS/iPad/iPhonePairing/iPhonePairingView.swift
  LivingStory-iOS/LivingStory-iOS/iPhone/iPadPairing/SubView/ConnectButtonView.swift
  LivingStory-iOS/LivingStory-iOS/iPhone/iPadPairing/SubView/WifiConnectView.swift
  LivingStory-iOS/LivingStory-iOS/iPhone/iPadPairing/ViewModel/iPadParingViewModel.swift
  LivingStory-iOS/LivingStory-iOS/iPhone/iPadPairing/iPadPairingView.swift
  LivingStory-iOS/LivingStory-iOS/iPhone/iPhoneFairyTale/FairyTaleStatusView.swift
  LivingStory-iOS/LivingStory-iOS/iPhone/iPhoneFairyTale/iPhoneFairyTaleView.swift
Labels: 🔥Feature, 🐣Demian

#51 feat/#49/iPhoneFairyTaleInteractionView 구현
  LivingStory-iOS/LivingStory-iOS.xcodeproj/project.pbxproj
  LivingStory-iOS/LivingStory-iOS/Core/Resources/Assets.xcassets/Lamp.imageset/Contents.json
  LivingStory-iOS/LivingStory-iOS/Core/Resources/Assets.xcassets/Lamp.imageset/Lamp.png
  LivingStory-iOS/LivingStory-iOS/iPhone/iPhoneFairyTale/AVFoundation/AudioInputModel.swift
  LivingStory-iOS/LivingStory-iOS/iPhone/iPhoneFairyTale/Fire2.json
  LivingStory-iOS/LivingStory-iOS/iPhone/iPhoneFairyTale/Lottie/FireAnimationView.swift
  LivingStory-iOS/LivingStory-iOS/iPhone/iPhoneFairyTale/Lottie/LottieView.swift
  LivingStory-iOS/LivingStory-iOS/iPhone/iPhoneFairyTale/iPhoneInteractionView.swift
Labels: 🔥Feature, 👹Martin

#63 feat/#59/페어링 뷰 와이파이 로띠 추가
  LivingStory-iOS/LivingStory-iOS.xcodeproj/project.pbxproj
  LivingStory-iOS/LivingStory-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  LivingStory-iOS/LivingStory-iOS/iPhone/iPadPairing/SubView/WifiConnectView.swift
  LivingStory-iOS/LivingStory-iOS/iPhone/iPadPairing/Wifi.json
  LivingStory-iOS/LivingStory-iOS/iPhone/iPadPairing/iPadPairingView.swift
  LivingStory-iOS/LivingStory-iOS/iPhone/iPhoneFairyTale/Fire.json
Labels: 🔥Feature, 💪Ito

#74 Feat/#60/아이폰 동화 뷰로 푸시
  LivingStory-iOS/LivingStory-iOS.xcodeproj/project.pbxproj
  LivingStory-iOS/LivingStory-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  LivingStory-iOS/LivingStory-iOS/iPhone/iPadPairing/SubView/ConnectedBookView.swift
  LivingStory-iOS/LivingStory-iOS/iPhone/iPadPairing/SubView/WifiConnectView.swift
  LivingStory-iOS/LivingStory-iOS/iPhone/iPadPairing/ViewModel/iPadParingViewModel.swift
  LivingStory-iOS/LivingStory-iOS/iPhone/iPadPairing/Wifi.json
  LivingStory-iOS/LivingStory-iOS/iPhone/iPadPairing/iPadPairingView.swift
  LivingStory-iOS/LivingStory-iOS/iPhone/iPhoneFairyTale/Fire.json
Labels: 🔥Feature, 💪Ito

#62 feat/#19/iPhoneIntroView 구현
  LivingStory-iOS/LivingStory-iOS/Core/Resources/Assets.xcassets/iPhoneIntro.imageset/Contents.json
  LivingStory-iOS/LivingStory-iOS/Core/Resources/Assets.xcassets/iPhoneIntro.imageset/iPhoneIntro.png
  LivingStory-iOS/LivingStory-iOS/iPhone/iPhoneIntro/iPhoneIntroView.swift
Labels: 🔥Feature, 🐣Demian

#76 chore/#61/ Lottie Resource 정리 및 iPhoneFairyTaleView 그룹 정리
  LivingStory-iOS/LivingStory-iOS.xcodeproj/project.pbxproj
  LivingStory-iOS/LivingStory-iOS/Core/Components/Lottie/LottieView.swift
  LivingStory-iOS/LivingStory-iOS/iPhone/iPadPairing/WifiConnectView.swift
  LivingStory-iOS/LivingStory-iOS/iPhone/iPhoneFairyTale/FairyTaleStatusView.swift
  LivingStory-iOS/LivingStory-iOS/iPhone/iPhoneFairyTale/Model/AVFoundation/AudioInputModel.swift
  LivingStory-iOS/LivingStory-iOS/iPhone/iPhoneFairyTale/Model/iPhoneFairyTaleModel.swift
  LivingStory-iOS/LivingStory-iOS/iPhone/iPhoneFairyTale/View/FireAnimationView.swift
  LivingStory-iOS/LivingStory-iOS/iPhone/iPhoneFairyTale/View/iPhoneInteractionView.swift
  LivingStory-iOS/LivingStory-iOS/iPhone/iPhoneFairyTale/ViewModel/iPhoneFairyTaleViewModel.swift
  LivingStory-iOS/LivingStory-iOS/iPhone/iPhoneFairyTale/iPhoneFairyTaleView.swift
  LivingStory-iOS/LivingStory-iOS/iPhone/iPhoneIntro/iPhoneIntroView.swift
Labels: 💪Ito, 🔍Chore

#82 Feat/#64/아이패드 씬 별 아이폰 인터렉션 반응에 따른 변화 구현 완료
  LivingStory-iOS/LivingStory-iOS.xcodeproj/project.pbxproj
  LivingStory-iOS/LivingStory-iOS/App/Coordinator/AppCoordinator.swift
  LivingStory-iOS/LivingStory-iOS/App/Coordinator/AppRoute.swift
  LivingStory-iOS/LivingStory-iOS/App/Factory/ModuleFactory.swift
  LivingStory-iOS/LivingStory-iOS/App/RootNavigationView.swift
  LivingStory-iOS/LivingStory-iOS/Core/Components/Alerts/InteractionComplete.swift
  LivingStory-iOS/LivingStory-iOS/Core/Modules/MultipeerModule/Enum/FairyTaleInteraction.swift
  LivingStory-iOS/LivingStory-iOS/Core/Modules/MultipeerModule/MultipeerManager+Extension.swift
  LivingStory-iOS/LivingStory-iOS/Core/Modules/MultipeerModule/MultipeerManager.swift
  LivingStory-iOS/LivingStory-iOS/Core/Modules/MultipeerModule/NotificationCenter/NotificationCenter+.swift
  LivingStory-iOS/LivingStory-iOS/Core/Resources/Assets.xcassets/HeungCover.imageset/Contents.json
  LivingStory-iOS/LivingStory-iOS/Core/Resources/Assets.xcassets/HeungCover.imageset/HeungCover.png
  LivingStory-iOS/LivingStory-iOS/iPad/iPadFairyTale/Model/FairyTaleModel.swift
  LivingStory-iOS/LivingStory-iOS/iPad/iPadFairyTale/View/FairyTaleInteractionView.swift
  LivingStory-iOS/LivingStory-iOS/iPad/iPadFairyTale/ViewModel/iPadFairyTaleViewModel.swift
  LivingStory-iOS/LivingStory-iOS/iPad/iPadFairyTale/iPadFairyTaleView.swift
  LivingStory-iOS/LivingStory-iOS/iPad/iPhonePairing/Model/BookSelectionSignal.swift
  LivingStory-iOS/LivingStory-iOS/iPad/iPhonePairing/ViewModel/iPhonePairingViewModel.swift
  LivingStory-iOS/LivingStory-iOS/iPhone/iPadPairing/SubView/ConnectedBookView.swift
  LivingStory-iOS/LivingStory-iOS/iPhone/iPadPairing/ViewModel/iPadParingViewModel.swift
  LivingStory-iOS/LivingStory-iOS/iPhone/iPadPairing/WifiConnectView.swift
  LivingStory-iOS/LivingStory-iOS/iPhone/iPadPairing/iPadPairingView.swift
  LivingStory-iOS/LivingStory-iOS/iPhone/iPhoneFairyTale/Model/AVFoundation/AudioInputModel.swift
  LivingStory-iOS/LivingStory-iOS/iPhone/iPhoneFairyTale/View/FireAnimationView.swift
  LivingStory-iOS/LivingStory-iOS/iPhone/iPhoneFairyTale/ViewModel/iPhoneFairyTaleViewModel.swift
  LivingStory-iOS/LivingStory-iOS/iPhone/iPhoneFairyTale/iPhoneFairyTaleView.swift
Labels: 🔥Feature, 🐣Demian

#86 chore/#85/App Icon 추가
  LivingStory-iOS/LivingStory-iOS/Core/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  LivingStory-iOS/LivingStory-iOS/Core/Resources/Assets.xcassets/AppIcon.appiconset/FairyTaleHomeAppIcon.jpeg
Labels: 💪Ito, 🔍Chore

#90 Chore/#89/흥부 스토리 HomeKit 연동 및 페이지 별 사운드 출력 세팅
  LivingStory-iOS/LivingStory-iOS.xcodeproj/project.pbxproj
  LivingStory-iOS/LivingStory-iOS/Core/Literals/SoundLiterals.swift
  LivingStory-iOS/LivingStory-iOS/Core/Modules/HomeKitModule/HomeKitManager.swift
  LivingStory-iOS/LivingStory-iOS/Core/Modules/HomeKitModule/HomeKitModels.swift
  LivingStory-iOS/LivingStory-iOS/Core/Resources/Assets.xcassets/EndingText.imageset/Contents.json
  LivingStory-iOS/LivingStory-iOS/Core/Resources/Assets.xcassets/EndingText.imageset/EndingText.png
  LivingStory-iOS/LivingStory-iOS/Core/Resources/Assets.xcassets/Heung6.imageset/Contents.json
  LivingStory-iOS/LivingStory-iOS/Core/Resources/Assets.xcassets/Heung6.imageset/Heung6.png
  LivingStory-iOS/LivingStory-iOS/Core/Resources/Assets.xcassets/HeungEnding.imageset/Contents.json
  LivingStory-iOS/LivingStory-iOS/Core/Resources/Assets.xcassets/HeungEnding.imageset/HeungEnding.png
  LivingStory-iOS/LivingStory-iOS/Core/Resources/Sound/Sawing1.m4a
  LivingStory-iOS/LivingStory-iOS/Core/Resources/Sound/Sawing2.m4a
  LivingStory-iOS/LivingStory-iOS/Core/Resources/Sounds/HeungEndingMusic.m4a
  LivingStory-iOS/LivingStory-iOS/Core/Resources/Sounds/HeungGold.wav
  LivingStory-iOS/LivingStory-iOS/Core/Resources/Sounds/Sawing1.m4a
  LivingStory-iOS/LivingStory-iOS/Core/Resources/Sounds/Sawing2.m4a
  LivingStory-iOS/LivingStory-iOS/Info.plist
  LivingStory-iOS/LivingStory-iOS/iPad/iPadFairyTale/Model/FairyTaleModel.swift
  LivingStory-iOS/LivingStory-iOS/iPad/iPadFairyTale/View/FairyTaleEnddingView.swift
  LivingStory-iOS/LivingStory-iOS/iPad/iPadFairyTale/View/FairyTaleLastPageButtonView.swift
  LivingStory-iOS/LivingStory-iOS/iPad/iPadFairyTale/ViewModel/iPadFairyTaleViewModel.swift
  LivingStory-iOS/LivingStory-iOS/iPad/iPadFairyTale/iPadFairyTaleView.swift
  LivingStory-iOS/LivingStory-iOS/iPhone/iPhoneFairyTale/Model/AVFoundation/AudioInputModel.swift
  LivingStory-iOS/LivingStory-iOS/iPhone/iPhoneFairyTale/Model/CoreMotion/CoreMotionManager.swift
  LivingStory-iOS/LivingStory-iOS/iPhone/iPhoneFairyTale/View/iPhoneHeungInteractionView.swift
Labels: 🔥Feature, 💪Ito, 🔍Chore

#92 Feat/#91/UI 피드백 수정
  LivingStory-iOS/LivingStory-iOS/Core/Components/Lottie/LottieView.swift
  LivingStory-iOS/LivingStory-iOS/Core/Modules/HomeKitModule/HomeKitModels.swift
  LivingStory-iOS/LivingStory-iOS/Core/Resources/Assets.xcassets/iPhoneNotice.imageset/iPhoneNotice.png
  LivingStory-iOS/LivingStory-iOS/iPad/iPadFairyTale/View/FairyTaleInteractionView.swift
  LivingStory-iOS/LivingStory-iOS/iPad/iPadFairyTale/View/iPadPigInteractionView.swift
  LivingStory-iOS/LivingStory-iOS/iPad/iPadFairyTale/ViewModel/iPadFairyTaleViewModel.swift
  LivingStory-iOS/LivingStory-iOS/iPad/iPadFairyTale/iPadFairyTaleView.swift
  LivingStory-iOS/LivingStory-iOS/iPad/iPhonePairing/View/SubView/PeerConnectButtonView.swift
  LivingStory-iOS/LivingStory-iOS/iPad/iPhonePairing/View/SubView/iPhoneNoticeTextView.swift
  LivingStory-iOS/LivingStory-iOS/iPhone/iPadPairing/SubView/ConnectButtonView.swift
  LivingStory-iOS/LivingStory-iOS/iPhone/iPadPairing/WifiConnectView.swift
  LivingStory-iOS/LivingStory-iOS/iPhone/iPhoneFairyTale/View/FireAnimationView.swift
Labels: 🔥Feature, ♽Refactor, 💪Ito
